name: AWS Instance Destroy

on:
  workflow_dispatch:


jobs:
  tf_fmt:
    name: Deployment
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Terraform Init
      id: init
      shell: bash    
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        [ -n "$LOG_LEVEL" ] && export TF_LOG="$LOG_LEVEL"
        terraform init -no-color -input=false

    - name: Terraform validate
      id: validate
      shell: bash
      run: |
        [ -n "$LOG_LEVEL" ] && export TF_LOG="$LOG_LEVEL"
        terraform validate -no-color


    - name: Terraform plan
      id: destroy
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform destroy -no-color -auto-approve -input=false


